server: { port: 8081 }
spring:
  application: { name: payments-service }
  datasource: { url: "jdbc:postgresql://127.0.0.1:5433/orbita?currentSchema=payments", username: orbita, password: orbita }
  jpa:
    hibernate: { ddl-auto: validate }
    properties: { hibernate: { default_schema: payments } }
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.sql
    default-schema: payments
  cache: { type: redis }
  data:
    redis: { host: localhost, port: 6379, timeout: 2s }
  kafka:
    bootstrap-servers: localhost:9092
    consumer: { auto-offset-reset: earliest, properties: { spring.json.trusted.packages: "*" } }
    producer: { value-serializer: org.apache.kafka.common.serialization.StringSerializer }
    consumer.properties.spring.json.value.default.type: java.lang.String
---
spring:
  config: { activate: { on-profile: docker } }
  datasource: { url: "jdbc:postgresql://postgres:5432/orbita?currentSchema=payments" }
  kafka: { bootstrap-servers: kafka:9092 }
  data: { redis: { host: redis, port: 6379 } }
