CREATE SCHEMA IF NOT EXISTS payments AUTHORIZATION orbita;
CREATE SCHEMA IF NOT EXISTS orders AUTHORIZATION orbita;
CREATE SCHEMA IF NOT EXISTS auth AUTHORIZATION orbita;
CREATE SCHEMA IF NOT EXISTS notifications AUTHORIZATION orbita;
